### ISSUE TITLE
Create Schedule of activities till the end of the course

### ISSUE THREAD

**Issue by bobbyreed** [geethikasreya/mentcare_project#4]
- Sprint 3 (10/1-10/3)
  - (activities go here)
  - (activities go here)
- Sprint 4 (10/3 - 10/8)
  - (activities go here)
  - (activities go here)

**Comment by JahnaviThavanti** [comment]
Sprint 3 (10/1-10/3)
UML diagrams
Schedule of implementation
One developed and functional service

Sprint 4 (10/3 - 10/8)
Software documentation 
Presentation
Essay describing
